/* 
 * TheAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines AdminAction
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum AdminAction
    {
        /// <summary>
        /// Enum IsPinned for value: IsPinned
        /// </summary>
        [EnumMember(Value = "IsPinned")]
        IsPinned = 1,

        /// <summary>
        /// Enum IsEssence for value: IsEssence
        /// </summary>
        [EnumMember(Value = "IsEssence")]
        IsEssence = 2,

        /// <summary>
        /// Enum Remove for value: Remove
        /// </summary>
        [EnumMember(Value = "Remove")]
        Remove = 3

    }

}
