/* 
 * TheAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines MemberRole
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum MemberRole
    {
        /// <summary>
        /// Enum Normal for value: Normal
        /// </summary>
        [EnumMember(Value = "Normal")]
        Normal = 1,

        /// <summary>
        /// Enum Admin for value: Admin
        /// </summary>
        [EnumMember(Value = "Admin")]
        Admin = 2,

        /// <summary>
        /// Enum Super for value: Super
        /// </summary>
        [EnumMember(Value = "Super")]
        Super = 3

    }

}
