/* 
 * TheAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines RequestStatus
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum RequestStatus
    {
        /// <summary>
        /// Enum Unhandled for value: Unhandled
        /// </summary>
        [EnumMember(Value = "Unhandled")]
        Unhandled = 1,

        /// <summary>
        /// Enum Accepted for value: Accepted
        /// </summary>
        [EnumMember(Value = "Accepted")]
        Accepted = 2,

        /// <summary>
        /// Enum Refused for value: Refused
        /// </summary>
        [EnumMember(Value = "Refused")]
        Refused = 3

    }

}
