/* 
 * TheAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines WorkType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum WorkType
    {
        /// <summary>
        /// Enum Book for value: Book
        /// </summary>
        [EnumMember(Value = "Book")]
        Book = 1,

        /// <summary>
        /// Enum Film for value: Film
        /// </summary>
        [EnumMember(Value = "Film")]
        Film = 2

    }

}
